import {
  computeAbo,
  computeAnnuitaet,
  computeBeton,
  computeBoden,
  computeCo2,
  computeFliesen,
  computeGeraet,
  computeGrundpreis,
  computeKfz,
  computeLed,
  computeMehrwertsteuer,
  computeMiete,
  computeMultipack,
  computeProzent,
  computeRabatt,
  computeRatenkauf,
  computeRoi,
  computeSparplan,
  computeStandby,
  computeStromkosten,
  computeTapete,
  computeVergleich,
  computeWandfarbe,
  computeZinseszins,
} from "@/lib/compute"
import type { Calculator, CalculatorField } from "@/lib/types"

const einheit: CalculatorField["kind"] = "select"

const mengenEinheit = {
  kind: einheit,
  options: [
    { value: "g", label: "Gramm (g)" },
    { value: "kg", label: "Kilogramm (kg)" },
    { value: "ml", label: "Milliliter (ml)" },
    { value: "l", label: "Liter (l)" },
    { value: "m", label: "Meter (m)" },
    { value: "stueck", label: "Stück" },
  ],
} as const

export const calculators: Calculator[] = [
  {
    slug: "zinseszins",
    title: "Zinseszins",
    description: "Endkapital und Zinsertrag, wenn der Zins mitverzinst wird.",
    category: "finanzen",
    keywords: ["zinsen", "zins", "anlage", "endkapital", "sparen", "verzinsung"],
    highlighted: true,
    fields: [
      { id: "kapital", label: "Startkapital", unit: "€", kind: "number", defaultValue: "10000", hint: "Der Betrag zum Start, ohne spätere Einzahlungen." },
      { id: "zins", label: "Jahreszins", unit: "%", kind: "number", defaultValue: "3", hint: "Nominalzins pro Jahr. Gebühren stecken hier nicht drin." },
      { id: "jahre", label: "Laufzeit", unit: "Jahre", kind: "number", defaultValue: "10" },
      {
        id: "rhythmus",
        label: "Zinsgutschrift",
        kind: "select",
        defaultValue: "jaehrlich",
        options: [
          { value: "jaehrlich", label: "jährlich" },
          { value: "vierteljaehrlich", label: "vierteljährlich" },
          { value: "monatlich", label: "monatlich" },
        ],
      },
    ],
    formula: [
      "Beim Zinseszins wird der Zins dem Kapital zugeschlagen und in der nächsten Periode mitverzinst.",
      "Wir teilen den Jahreszins durch die Zahl der Gutschriften im Jahr (1, 4 oder 12) und rechnen über alle Perioden der Laufzeit.",
      "Endkapital = Startkapital × (1 + Jahreszins ÷ 100 ÷ Perioden) ^ (Perioden × Jahre).",
      "Der Zinsertrag ist die Differenz der auf Cent gerundeten Beträge.",
    ],
    tip: "Ein kleiner Zinsunterschied wiegt mit den Jahren schwerer als ein etwas höheres Startkapital. Wenn die Bank einen Effektivzins nennt, vergleich den: der Nominalzins lässt Gebühren außen vor.",
    related: ["sparplan", "annuitaetenkredit", "roi"],
    compute: computeZinseszins,
  },
  {
    slug: "annuitaetenkredit",
    title: "Annuitätenkredit",
    description: "Monatliche Rate, Gesamtzahlung und der Zinsanteil eines Ratenkredits.",
    category: "finanzen",
    keywords: ["kredit", "rate", "annuität", "darlehen", "zins", "tilgung"],
    fields: [
      { id: "kredit", label: "Kreditbetrag", unit: "€", kind: "number", defaultValue: "250000" },
      { id: "zins", label: "Jahreszins", unit: "%", kind: "number", defaultValue: "3.5", hint: "Nominalzins pro Jahr, umgelegt auf den Monat." },
      { id: "jahre", label: "Laufzeit", unit: "Jahre", kind: "number", defaultValue: "25" },
    ],
    formula: [
      "Eine Annuität ist eine gleichbleibende Rate aus Zins und Tilgung. Am Anfang ist der Zinsanteil hoch, später die Tilgung.",
      "Der Monatszins ist der Jahreszins geteilt durch 12. Die Zahl der Raten ist die Laufzeit in Jahren mal 12.",
      "Rate = Kredit × (Monatszins × (1 + Monatszins) ^ Monate) ÷ ((1 + Monatszins) ^ Monate − 1). Bei 0 % Zins ist die Rate einfach Kredit geteilt durch Monate.",
      "Wir runden die Rate auf den Cent. Die Gesamtzahlung ist diese gerundete Rate mal die Anzahl der Monate.",
    ],
    tip: "Die Rate hier ist nur Zins und Tilgung. Bereitstellungszinsen, eine Restschuldversicherung oder eine Sondertilgung ändern die Summe. Eine Sondertilgung am Anfang spart mehr Zinsen als derselbe Betrag am Ende.",
    related: ["zinseszins", "ratenkauf", "roi"],
    compute: computeAnnuitaet,
  },
  {
    slug: "sparplan",
    title: "Sparplan",
    description: "Was aus Startkapital und einer monatlichen Einzahlung bis zum Zieljahr wird.",
    category: "finanzen",
    keywords: ["sparen", "sparrate", "etf", "dauerauftrag", "zins", "vermögensaufbau"],
    fields: [
      { id: "start", label: "Startkapital", unit: "€", kind: "number", defaultValue: "1000" },
      { id: "rate", label: "Monatliche Einzahlung", unit: "€", kind: "number", defaultValue: "150" },
      { id: "zins", label: "Jahreszins", unit: "%", kind: "number", defaultValue: "3", hint: "Angenommene durchschnittliche Rendite pro Jahr." },
      { id: "jahre", label: "Laufzeit", unit: "Jahre", kind: "number", defaultValue: "15" },
    ],
    formula: [
      "Das Startkapital wächst wie beim Zinseszins, mit monatlicher Verzinsung.",
      "Die Einzahlungen rechnen wir nachschüssig: Jede Rate kommt am Monatsende und wird danach mitverzinst.",
      "Endwert der Raten = Rate × ((1 + Monatszins) ^ Monate − 1) ÷ Monatszins. Bei 0 % Zins ist es einfach Rate mal Monate.",
      "Das Guthaben ist Startkapital plus Endwert der Raten. Geldbeträge zeigen wir auf den Cent.",
    ],
    tip: "Die Rechnung geht von einer Einzahlung am Monatsende aus. Ein fester Dauerauftrag schlägt das Warten auf den passenden Monat: fehlende Raten holt der Zins selten wieder rein.",
    related: ["zinseszins", "roi", "abo-jahreskosten"],
    compute: computeSparplan,
  },
  {
    slug: "mehrwertsteuer",
    title: "Mehrwertsteuer",
    description: "Netto, Steuer und Brutto bei 19 % oder 7 %.",
    category: "finanzen",
    keywords: ["mwst", "umsatzsteuer", "netto", "brutto", "steuer", "19", "7"],
    fields: [
      { id: "betrag", label: "Betrag", unit: "€", kind: "number", defaultValue: "100" },
      {
        id: "richtung",
        label: "Der Betrag ist",
        kind: "select",
        defaultValue: "netto-zu-brutto",
        options: [
          { value: "netto-zu-brutto", label: "netto, Brutto gesucht" },
          { value: "brutto-zu-netto", label: "brutto, Netto gesucht" },
        ],
      },
      {
        id: "satz",
        label: "Steuersatz",
        kind: "select",
        defaultValue: "19",
        options: [
          { value: "19", label: "19 %" },
          { value: "7", label: "7 %" },
        ],
      },
    ],
    formula: [
      "Der Regelsteuersatz beträgt 19 %, der ermäßigte Satz 7 %. Welcher Satz gilt, steht im Umsatzsteuergesetz und hängt von der Ware ab, nicht vom Wunsch.",
      "Aus netto wird brutto mit Brutto = Netto × (1 + Satz). Die Steuer ist Netto × Satz.",
      "Aus brutto wird netto mit Netto = Brutto ÷ (1 + Satz).",
      "Angezeigte Beträge sind auf Cent gerundet. Die Steuer setzen wir als Differenz, damit Netto, Steuer und Brutto zusammenpassen.",
    ],
    tip: "Auf dem Kassenbon ist der Bruttopreis die Pflicht. Den Nettopreis brauchst du vor allem, wenn du Vorsteuer ziehen darfst. 7 % gelten nur für begünstigte Waren, nicht pauschal für alles Essbare.",
    related: ["prozentrechnung", "rabatt", "grundpreis"],
    compute: computeMehrwertsteuer,
  },
  {
    slug: "prozentrechnung",
    title: "Prozentrechnung",
    description: "Anteil, Prozentsatz oder Veränderung in einem Rechner.",
    category: "finanzen",
    keywords: ["prozent", "rabatt", "steigerung", "anteil", "prozentwert"],
    fields: [
      {
        id: "modus",
        label: "Was willst du wissen?",
        kind: "select",
        defaultValue: "anteil",
        options: [
          { value: "anteil", label: "Wie viel sind p % von einem Wert?" },
          { value: "satz", label: "Wie viel Prozent ist ein Teil vom Ganzen?" },
          { value: "veraenderung", label: "Um wie viel Prozent ändert sich ein Wert?" },
        ],
      },
      { id: "basis", label: "Grundwert", kind: "number", defaultValue: "200", showWhen: { id: "modus", value: "anteil" } },
      { id: "prozent", label: "Prozent", unit: "%", kind: "number", defaultValue: "19", showWhen: { id: "modus", value: "anteil" } },
      { id: "teil", label: "Prozentwert", kind: "number", defaultValue: "50", showWhen: { id: "modus", value: "satz" } },
      { id: "ganzes", label: "Grundwert", kind: "number", defaultValue: "200", showWhen: { id: "modus", value: "satz" } },
      { id: "von", label: "Ausgangswert", kind: "number", defaultValue: "80", showWhen: { id: "modus", value: "veraenderung" } },
      { id: "nach", label: "Neuer Wert", kind: "number", defaultValue: "100", showWhen: { id: "modus", value: "veraenderung" } },
    ],
    formula: [
      "Drei Fragen, eine Rechnung. Anteil: Grundwert × Prozent ÷ 100.",
      "Prozentsatz: Prozentwert ÷ Grundwert × 100. Der Grundwert darf nicht 0 sein.",
      "Veränderung: (neuer Wert − Ausgangswert) ÷ Ausgangswert × 100. Ein Rückgang wird negativ. Der Ausgangswert darf nicht 0 sein.",
    ],
    tip: "Zwei Rabatte nacheinander, erst 20 % und dann 10 %, sind nicht 30 %. Der zweite Rabatt bezieht sich auf den schon reduzierten Preis.",
    related: ["rabatt", "mehrwertsteuer", "roi"],
    compute: computeProzent,
  },
  {
    slug: "roi",
    title: "Einfacher ROI",
    description: "Rendite aus Einsatz und Rückfluss, ohne die Dauer zu gewichten.",
    category: "finanzen",
    keywords: ["roi", "rendite", "gewinn", "investition", "return"],
    fields: [
      { id: "einsatz", label: "Einsatz", unit: "€", kind: "number", defaultValue: "5000" },
      { id: "rueckfluss", label: "Rückfluss", unit: "€", kind: "number", defaultValue: "6200", hint: "Was am Ende zurückkommt, inklusive des Einsatzes." },
    ],
    formula: [
      "ROI heißt hier return on investment, schlicht als Verhältnis.",
      "Gewinn = Rückfluss − Einsatz. ROI = Gewinn ÷ Einsatz × 100.",
      "Die Laufzeit spielt keine Rolle. 10 % in einem Jahr sind etwas anderes als 10 % in fünf Jahren.",
      "Der Einsatz darf nicht 0 sein. Geldbeträge runden wir auf den Cent, den Prozentsatz auf zwei Stellen.",
    ],
    tip: "Für einen Vergleich über unterschiedliche Zeiträume brauchst du eine jährliche Größe, zum Beispiel den Zinseszins. Dieser ROI sagt nur, ob der Rückfluss über dem Einsatz lag.",
    related: ["zinseszins", "sparplan", "prozentrechnung"],
    compute: computeRoi,
  },
  {
    slug: "stromkosten",
    title: "Stromkosten",
    description: "Was ein Verbrauch in Kilowattstunden im Monat und im Jahr kostet.",
    category: "verbraucherfragen",
    keywords: ["strom", "kwh", "arbeitspreis", "rechnung", "energie"],
    highlighted: true,
    fields: [
      { id: "verbrauch", label: "Verbrauch", unit: "kWh", kind: "number", defaultValue: "250" },
      {
        id: "zeitraum",
        label: "Der Verbrauch gilt",
        kind: "select",
        defaultValue: "monat",
        options: [
          { value: "monat", label: "pro Monat" },
          { value: "jahr", label: "pro Jahr" },
        ],
      },
      { id: "preis", label: "Arbeitspreis", unit: "ct/kWh", kind: "number", defaultValue: "35", hint: "Steht auf der Rechnung, getrennt vom Grundpreis. 35 Cent sind ein Beispiel." },
    ],
    formula: [
      "Kosten = Verbrauch in kWh × Arbeitspreis. Den Preis in Cent teilen wir durch 100, damit Euro herauskommen.",
      "Gibst du den Verbrauch pro Monat an, malnehmen wir mit 12 für das Jahr. Gibst du das Jahr an, teilen wir durch 12 für den Monat.",
      "Der Grundpreis der Tarifs fehlt hier bewusst. Er fällt auch bei wenig Verbrauch an.",
    ],
    tip: "Der Arbeitspreis in Cent je kWh steht auf der Rechnung, oft unter dem Grundpreis. Wer nur den Verbrauch rechnet, unterschätzt die Jahresrechnung um zwölf Grundpreise.",
    related: ["geraetestromverbrauch", "standby-kosten", "co2-aus-strom"],
    compute: computeStromkosten,
  },
  {
    slug: "mietbelastungsquote",
    title: "Mietbelastungsquote",
    description: "Welchen Anteil die Warmmiete am Haushaltsnettoeinkommen hat.",
    category: "verbraucherfragen",
    keywords: ["miete", "warmmiete", "einkommen", "wohnung", "quote"],
    fields: [
      { id: "miete", label: "Monatliche Warmmiete", unit: "€", kind: "number", defaultValue: "950", hint: "Kaltmiete plus Nebenkosten, so wie sie monatlich abgehen." },
      { id: "einkommen", label: "Monatliches Haushaltsnettoeinkommen", unit: "€", kind: "number", defaultValue: "3200" },
    ],
    formula: [
      "Quote = Warmmiete ÷ Haushaltsnettoeinkommen × 100.",
      "Beide Beträge müssen denselben Zeitraum meinen, hier einen Monat.",
      "Wir runden die Quote auf eine Nachkommastelle.",
    ],
    tip: "Als grobe Orientierung gilt: liegt die Warmmiete dauerhaft über etwa 30 % des Haushaltsnettos, wird der Spielraum für Rücklagen dünn. Heiznachzahlungen gehören in diese Betrachtung, nicht nur die Kaltmiete.",
    related: ["stromkosten", "abo-jahreskosten", "kfz-kosten-pro-km"],
    compute: computeMiete,
  },
  {
    slug: "kfz-kosten-pro-km",
    title: "Kfz-Kosten pro km",
    description: "Sprit und fixe Jahreskosten, umgelegt auf die gefahrenen Kilometer.",
    category: "verbraucherfragen",
    keywords: ["auto", "kfz", "sprit", "kilometer", "versicherung", "wertverlust"],
    fields: [
      { id: "km", label: "Jahreskilometer", unit: "km", kind: "number", defaultValue: "12000" },
      { id: "verbrauch", label: "Verbrauch", unit: "l/100 km", kind: "number", defaultValue: "6.5" },
      { id: "sprit", label: "Kraftstoffpreis", unit: "€/l", kind: "number", defaultValue: "1.75" },
      { id: "versicherung", label: "Versicherung im Jahr", unit: "€", kind: "number", defaultValue: "700" },
      { id: "steuer", label: "Kfz-Steuer im Jahr", unit: "€", kind: "number", defaultValue: "120" },
      { id: "wartung", label: "Wartung und Verschleiß im Jahr", unit: "€", kind: "number", defaultValue: "450" },
      { id: "wertverlust", label: "Wertverlust im Jahr", unit: "€", kind: "number", defaultValue: "1800", hint: "Grober Jahresverlust, auch wenn kein Geld fließt." },
    ],
    formula: [
      "Kraftstoff je Kilometer = (Liter je 100 km ÷ 100) × Preis je Liter.",
      "Kraftstoff im Jahr = Kraftstoff je Kilometer × Jahreskilometer.",
      "Fixe Kosten = Versicherung + Steuer + Wartung + Wertverlust.",
      "Kosten je Kilometer = (Kraftstoff im Jahr + fixe Kosten) ÷ Jahreskilometer.",
    ],
    tip: "Der Wertverlust ist oft der größte Posten und steht auf keiner Werkstattrechnung. Wer ihn weglässt, rechnet das Auto zu billig. Beim Spritpreis nimm einen Wert, den du über ein paar Tankfüllungen gesehen hast.",
    related: ["stromkosten", "mietbelastungsquote", "co2-aus-strom"],
    compute: computeKfz,
  },
  {
    slug: "abo-jahreskosten",
    title: "Abo-Jahreskosten",
    description: "Aus dem Monatspreis werden Jahr, drei Jahre und ein Tagessatz.",
    category: "verbraucherfragen",
    keywords: ["abo", "abonnement", "streaming", "mitgliedschaft", "monatspreis"],
    fields: [
      { id: "monat", label: "Monatspreis", unit: "€", kind: "number", defaultValue: "9.99" },
    ],
    formula: [
      "Jahreskosten = Monatspreis × 12.",
      "Drei Jahre = Jahreskosten × 3.",
      "Der Tagessatz teilt das Jahr durch 365, ohne Schaltjahr.",
    ],
    tip: "Der Monatspreis wirkt klein. Auf drei Jahre gerechnet steht er neben Anschaffungen, die du dir sonst zweimal überlegen würdest. Mindestlaufzeit und Kündigungsfrist stehen im Vertrag, nicht im Preis.",
    related: ["multipack-stueckpreis", "stromkosten", "sparplan"],
    compute: computeAbo,
  },
  {
    slug: "geraetestromverbrauch",
    title: "Gerätestromverbrauch",
    description: "Aus Watt, Laufzeit und Strompreis wird der Jahresverbrauch.",
    category: "energiesparen",
    keywords: ["gerät", "watt", "kwh", "verbrauch", "strom", "haushalt"],
    fields: [
      { id: "watt", label: "Leistung", unit: "W", kind: "number", defaultValue: "150", hint: "Anschlussleistung vom Typenschild, oder ein gemessener Mittelwert." },
      { id: "stunden", label: "Betriebsstunden pro Tag", unit: "h", kind: "number", defaultValue: "4" },
      { id: "tage", label: "Tage im Jahr", unit: "Tage", kind: "number", defaultValue: "365" },
      { id: "preis", label: "Strompreis", unit: "€/kWh", kind: "number", defaultValue: "0.35" },
    ],
    formula: [
      "Kilowattstunden = Watt × Stunden pro Tag × Tage ÷ 1000.",
      "Kosten = Kilowattstunden × Preis je kWh.",
      "Das Typenschild nennt oft die höchste Leistung, nicht den Durchschnitt über die Stunde.",
    ],
    tip: "Ein Backofen mit 3.000 Watt heizt nicht die ganze Stunde mit voller Leistung. Für einen ehrlichen Wert miss das Gerät einmal mit einem Strommessgerät, gerade bei Waschmaschine und Kühlschrank.",
    related: ["stromkosten", "led-ersparnis", "standby-kosten"],
    compute: computeGeraet,
  },
  {
    slug: "led-ersparnis",
    title: "LED-Ersparnis",
    description: "Wie viel Strom und Geld LEDs gegenüber Glühbirnen im Jahr sparen.",
    category: "energiesparen",
    keywords: ["led", "glühbirne", "lampe", "watt", "sparen", "leuchtmittel"],
    highlighted: true,
    fields: [
      { id: "alt", label: "Leistung der Glühbirne", unit: "W", kind: "number", defaultValue: "60" },
      { id: "neu", label: "Leistung der LED", unit: "W", kind: "number", defaultValue: "8" },
      { id: "stunden", label: "Brennzeit pro Tag", unit: "h", kind: "number", defaultValue: "3" },
      { id: "tage", label: "Tage im Jahr", unit: "Tage", kind: "number", defaultValue: "365" },
      { id: "anzahl", label: "Anzahl Lampen", unit: "Stück", kind: "number", defaultValue: "6", integer: true },
      { id: "preis", label: "Strompreis", unit: "€/kWh", kind: "number", defaultValue: "0.35" },
    ],
    formula: [
      "Für beide Lampen gilt: kWh = Watt × Stunden × Tage × Anzahl ÷ 1000.",
      "Die Ersparnis in kWh ist der Verbrauch der Glühbirnen minus der Verbrauch der LEDs.",
      "Die Ersparnis in Euro ist diese Differenz mal den Strompreis. Der Kaufpreis der Lampen ist nicht enthalten.",
    ],
    tip: "Vergleich Lumen, nicht Watt. Eine LED mit 8 Watt ersetzt oft eine alte 60-Watt-Birne, eine sparsame mit zu wenig Lumen wirkt nur dunkler. Lichtfarbe in Kelvin ändert den Komfort, nicht diese Stromrechnung.",
    related: ["geraetestromverbrauch", "standby-kosten", "stromkosten"],
    compute: computeLed,
  },
  {
    slug: "standby-kosten",
    title: "Standby-Kosten",
    description: "Was Geräte im Leerlauf über das Jahr an Strom kosten.",
    category: "energiesparen",
    keywords: ["standby", "leerlauf", "netzteil", "stand-by", "strom"],
    fields: [
      { id: "watt", label: "Leistung im Standby", unit: "W", kind: "number", defaultValue: "5" },
      { id: "stunden", label: "Standby-Stunden pro Tag", unit: "h", kind: "number", defaultValue: "18", hint: "Die Zeit, in der das Gerät nicht arbeitet, aber eingesteckt bleibt." },
      { id: "preis", label: "Strompreis", unit: "€/kWh", kind: "number", defaultValue: "0.35" },
    ],
    formula: [
      "Wir rechnen mit 365 Tagen.",
      "kWh = Watt × Standby-Stunden pro Tag × 365 ÷ 1000.",
      "Kosten = kWh × Preis je kWh.",
    ],
    tip: "Mehrere kleine Netzteile summieren sich. Eine schaltbare Steckdosenleiste macht aus ein paar Watt über Nacht null — außer bei Geräten, die eine Uhr oder ein Update brauchen.",
    related: ["geraetestromverbrauch", "stromkosten", "led-ersparnis"],
    compute: computeStandby,
  },
  {
    slug: "co2-aus-strom",
    title: "CO₂ aus Stromverbrauch",
    description: "Kilowattstunden, umgerechnet mit dem Emissionsfaktor des Strommix 2024.",
    category: "energiesparen",
    keywords: ["co2", "emission", "klima", "strommix", "kwh", "umwelt"],
    fields: [
      { id: "verbrauch", label: "Stromverbrauch", unit: "kWh", kind: "number", defaultValue: "3000", hint: "Zum Beispiel der Jahresverbrauch aus der Stromrechnung." },
    ],
    assumptions: [
      "353 g CO₂ je kWh. Das ist der vorläufige direkte CO₂-Emissionsfaktor des deutschen Stromverbrauchs für 2024 laut Umweltbundesamt, ohne Vorketten. Ein später veröffentlichter Jahreswert kann davon abweichen. Ökostromverträge und Vorketten (Herstellung der Anlagen, Brennstofflieferung) sind nicht eingerechnet.",
    ],
    formula: [
      "Kilogramm CO₂ = Verbrauch in kWh × 353 g/kWh ÷ 1000.",
      "Tonnen = Kilogramm ÷ 1000.",
      "Der Faktor beschreibt den deutschen Strommix 2024, nicht den Vertrag auf deiner Rechnung.",
    ],
    tip: "Weniger Kilowattstunden wirken in jedem Tarif. Ein Ökostromvertrag ändert die Marktbilanz, setzt die physikalische Erzeugung an deiner Steckdose aber nicht auf null.",
    related: ["stromkosten", "geraetestromverbrauch", "kfz-kosten-pro-km"],
    compute: computeCo2,
  },
  {
    slug: "wandfarbe",
    title: "Wandfarbe",
    description: "Liter und Gebinde aus Fläche, Anstrichen und Reichweite.",
    category: "heimwerken",
    keywords: ["farbe", "streichen", "wand", "anstrich", "liter", "dispersionsfarbe"],
    highlighted: true,
    fields: [
      { id: "flaeche", label: "Wandfläche", unit: "m²", kind: "number", defaultValue: "52", hint: "Länge mal Höhe aller Wände, bevor du Türen abziehst." },
      { id: "abzuege", label: "Abzüge für Türen und Fenster", unit: "m²", kind: "number", defaultValue: "6" },
      { id: "anstriche", label: "Anstriche", unit: "Stück", kind: "number", defaultValue: "2" },
      { id: "reichweite", label: "Reichweite", unit: "m²/l", kind: "number", defaultValue: "8", hint: "Steht auf dem Eimer, oft als Quadratmeter je Liter und Anstrich." },
      { id: "gebinde", label: "Gebindegröße", unit: "l", kind: "number", defaultValue: "10" },
    ],
    formula: [
      "Zu streichende Fläche = Wandfläche − Abzüge. Wird das negativ, bleibt null.",
      "Liter = Fläche × Anstriche ÷ Reichweite in m² je Liter.",
      "Die Zahl der Gebinde ist die Literzahl geteilt durch die Gebindegröße, auf ganze Eimer aufgerundet.",
    ],
    tip: "Ecken, Strukturputz und ein dunkler Untergrund schlucken mehr Farbe als die Reichweite auf dem Eimer. Halt eine Gebindegröße in Reserve, solange der Farbton noch gemischt werden kann.",
    related: ["tapetenbedarf", "fliesenbedarf", "bodenbelag"],
    compute: computeWandfarbe,
  },
  {
    slug: "tapetenbedarf",
    title: "Tapetenbedarf",
    description: "Rollen aus Umfang, Raumhöhe und dem Maß der Rolle, inklusive Rapport.",
    category: "heimwerken",
    keywords: ["tapete", "rolle", "rapport", "bahn", "renovieren"],
    fields: [
      { id: "umfang", label: "Raumumfang", unit: "m", kind: "number", defaultValue: "18", hint: "Zweimal Länge plus zweimal Breite, abzüglich sehr breiter Türöffnungen nur wenn du dort keine Bahn planst." },
      { id: "hoehe", label: "Raumhöhe", unit: "m", kind: "number", defaultValue: "2.5" },
      { id: "breite", label: "Rollenbreite", unit: "m", kind: "number", defaultValue: "0.53", hint: "0,53 m ist das übliche Maß einer Euro-Rolle." },
      { id: "laenge", label: "Rollenlänge", unit: "m", kind: "number", defaultValue: "10.05", hint: "10,05 m ist die übliche Länge einer Euro-Rolle." },
      { id: "rapport", label: "Rapport", unit: "m", kind: "number", defaultValue: "0", hint: "0, wenn das Muster nicht versetzt angesetzt werden muss. Sonst der Rapport von der Rolle, in Metern." },
    ],
    formula: [
      "Bahnen = Raumumfang ÷ Rollenbreite, aufgerundet.",
      "Die Bahnhöhe ist Raumhöhe plus Rapport. Ganze Bahnen je Rolle = Rollenlänge geteilt durch Bahnhöhe, abgerundet.",
      "Rollen = Bahnen ÷ Bahnen je Rolle, aufgerundet. Passt keine ganze Bahn auf eine Rolle, braucht jede Bahn entsprechend mehr Rollen.",
    ],
    tip: "Rapport heißt: das Muster muss an der nächsten Bahn wieder passen, du schneidest Verschnitt ab. Kauf Rollen aus derselben Anfertigungsnummer, die steht auf dem Einleger.",
    related: ["wandfarbe", "fliesenbedarf", "bodenbelag"],
    compute: computeTapete,
  },
  {
    slug: "fliesenbedarf",
    title: "Fliesenbedarf",
    description: "Stückzahl aus Fläche, Fliesenmaß und Verschnitt.",
    category: "heimwerken",
    keywords: ["fliesen", "verschnitt", "bad", "quadratmeter", "fliesenspiegel"],
    fields: [
      { id: "flaeche", label: "Fläche", unit: "m²", kind: "number", defaultValue: "15" },
      { id: "laenge", label: "Fliesenlänge", unit: "cm", kind: "number", defaultValue: "60" },
      { id: "breite", label: "Fliesenbreite", unit: "cm", kind: "number", defaultValue: "60" },
      { id: "verschnitt", label: "Verschnitt", unit: "%", kind: "number", defaultValue: "10", hint: "10 % bei gerader Verlegung, eher 15 % bei Diagonalverband." },
    ],
    formula: [
      "Fläche einer Fliese = Länge in Metern × Breite in Metern.",
      "Bedarf in m² = Fläche × (1 + Verschnitt ÷ 100).",
      "Stückzahl = Bedarf ÷ Fläche einer Fliese, auf ganze Fliesen aufgerundet.",
    ],
    tip: "Zehn Prozent reichen für gerade Verlegung und ein paar Schnitte. Diagonal, versetzt oder viele Anschlüsse brauchen eher 15 %. Eine Reserve für späteren Bruch ist billiger als eine zweite Lieferung mit anderem Farbstich.",
    related: ["bodenbelag", "wandfarbe", "betonmenge"],
    compute: computeFliesen,
  },
  {
    slug: "bodenbelag",
    title: "Bodenbelag",
    description: "Quadratmeter und Pakete für den Raum, mit Verschnitt.",
    category: "heimwerken",
    keywords: ["boden", "laminat", "parkett", "vinyl", "paket", "verschnitt"],
    fields: [
      { id: "laenge", label: "Raumlänge", unit: "m", kind: "number", defaultValue: "4.2" },
      { id: "breite", label: "Raumbreite", unit: "m", kind: "number", defaultValue: "3.6" },
      { id: "verschnitt", label: "Verschnitt", unit: "%", kind: "number", defaultValue: "8" },
      { id: "paket", label: "Inhalt je Paket", unit: "m²", kind: "number", defaultValue: "2.2", hint: "Steht auf dem Paket, oft um 2 m²." },
    ],
    formula: [
      "Raumfläche = Länge × Breite.",
      "Bedarf = Raumfläche × (1 + Verschnitt ÷ 100).",
      "Pakete = Bedarf ÷ Inhalt je Paket, auf ganze Pakete aufgerundet.",
    ],
    tip: "Miss die längste und die breiteste Stelle, inklusive Nischen. Türzargen fressen leicht eine Reihe. Lass Pakete vor dem Verlegen im Raum akklimatisieren, das steht auf der Packung.",
    related: ["fliesenbedarf", "tapetenbedarf", "wandfarbe"],
    compute: computeBoden,
  },
  {
    slug: "betonmenge",
    title: "Betonmenge",
    description: "Volumen in Kubikmeter und Liter, plus Säcke nach der Ergiebigkeit.",
    category: "heimwerken",
    keywords: ["beton", "estrich", "kubikmeter", "sack", "fundament"],
    fields: [
      { id: "laenge", label: "Länge", unit: "m", kind: "number", defaultValue: "3" },
      { id: "breite", label: "Breite", unit: "m", kind: "number", defaultValue: "0.8" },
      { id: "dicke", label: "Dicke", unit: "cm", kind: "number", defaultValue: "15" },
      { id: "ergiebigkeit", label: "Ergiebigkeit je 25-kg-Sack", unit: "l", kind: "number", defaultValue: "12", hint: "Fertiger Frischbeton je Sack. 12 Liter sind ein üblicher Richtwert, wenn der Sack nichts anderes sagt." },
    ],
    assumptions: [
      "Voreingestellt sind 12 Liter fertiger Beton je 25-kg-Sack, also 0,012 m³. Das ist ein Richtwert, keine Norm. Die Zahl auf deinem Sack ersetzt sie.",
    ],
    formula: [
      "Volumen in m³ = Länge × Breite × (Dicke in cm ÷ 100).",
      "Liter = Kubikmeter × 1000.",
      "Säcke = Volumen ÷ (Ergiebigkeit in Litern ÷ 1000), auf ganze Säcke aufgerundet.",
    ],
    tip: "Lieber eine Sackzugabe einplanen als mitten in der Fläche neu zu mischen. Die Ergiebigkeit auf dem Sack meint fertigen Frischbeton, nicht das Schüttvolumen des trockenen Pulvers.",
    related: ["bodenbelag", "fliesenbedarf", "wandfarbe"],
    compute: computeBeton,
  },
  {
    slug: "rabatt",
    title: "Rabatt",
    description: "Neuer Preis und Ersparnis bei einem prozentualen Nachlass.",
    category: "shopping",
    keywords: ["rabatt", "prozent", "sale", "reduziert", "angebot"],
    highlighted: true,
    fields: [
      { id: "preis", label: "Ursprünglicher Preis", unit: "€", kind: "number", defaultValue: "49.99" },
      { id: "rabatt", label: "Rabatt", unit: "%", kind: "number", defaultValue: "20" },
    ],
    formula: [
      "Ersparnis = Preis × Rabatt ÷ 100.",
      "Neuer Preis = Preis − Ersparnis.",
      "Wir runden den neuen Preis auf den Cent. Die angezeigte Ersparnis ist die Differenz zum gerundeten Ausgangspreis, damit beides zusammen den Ausgangspreis ergibt.",
    ],
    tip: "„Bis zu 50 %“ sagt nichts über den Artikel in deiner Hand. Rechne den konkreten Preis und vergleich ihn mit dem Grundpreis: ein hoher Rabatt auf eine kleine Packung kann teurer sein als die große ohne Störer.",
    related: ["grundpreis", "angebotsvergleich", "prozentrechnung"],
    compute: computeRabatt,
  },
  {
    slug: "grundpreis",
    title: "Grundpreis",
    description: "Preis je Kilogramm, Liter, Meter oder Stück, wie auf dem Preisschild.",
    category: "shopping",
    keywords: ["grundpreis", "kilopreis", "preis je kg", "pangv", "einheit"],
    highlighted: true,
    fields: [
      { id: "preis", label: "Preis", unit: "€", kind: "number", defaultValue: "2.49" },
      { id: "menge", label: "Menge", kind: "number", defaultValue: "400" },
      { id: "einheit", label: "Einheit", kind: "select", defaultValue: "g", options: [...mengenEinheit.options] },
    ],
    formula: [
      "Der Grundpreis bezieht sich auf eine vergleichbare Menge: 1 kg, 1 l, 1 m oder 1 Stück.",
      "Gramm rechnen wir in Kilogramm um (÷ 1000), Milliliter in Liter.",
      "Grundpreis = Preis ÷ Menge in der Bezugsgröße. Zusätzlich zeigen wir den Preis je eingegebener Einheit.",
    ],
    tip: "Die Preisangabenverordnung will den Grundpreis, damit Packungsgrößen vergleichbar werden. Achte auf die Einheit: 100 g auf dem einen Schild und 1 kg auf dem anderen lassen sich nicht auf einen Blick vergleichen.",
    related: ["angebotsvergleich", "multipack-stueckpreis", "rabatt"],
    compute: computeGrundpreis,
  },
  {
    slug: "angebotsvergleich",
    title: "Angebotsvergleich",
    description: "Bis zu drei Angebote, verglichen über den Grundpreis.",
    category: "shopping",
    keywords: ["angebot", "vergleich", "günstig", "grundpreis", "drei"],
    fields: [
      { id: "a1preis", label: "Preis", unit: "€", kind: "number", defaultValue: "1.89", group: "Angebot 1" },
      { id: "a1menge", label: "Menge", kind: "number", defaultValue: "500", group: "Angebot 1" },
      { id: "a1einheit", label: "Einheit", kind: "select", defaultValue: "g", group: "Angebot 1", options: [...mengenEinheit.options] },
      { id: "a2preis", label: "Preis", unit: "€", kind: "number", defaultValue: "3.29", group: "Angebot 2" },
      { id: "a2menge", label: "Menge", kind: "number", defaultValue: "1", group: "Angebot 2" },
      { id: "a2einheit", label: "Einheit", kind: "select", defaultValue: "kg", group: "Angebot 2", options: [...mengenEinheit.options] },
      { id: "a3preis", label: "Preis", unit: "€", kind: "number", defaultValue: "0.99", group: "Angebot 3" },
      { id: "a3menge", label: "Menge", kind: "number", defaultValue: "250", group: "Angebot 3" },
      { id: "a3einheit", label: "Einheit", kind: "select", defaultValue: "g", group: "Angebot 3", options: [...mengenEinheit.options] },
    ],
    formula: [
      "Jedes Angebot bekommt einen Grundpreis, genau wie im Grundpreis-Rechner.",
      "Leere Angebote lässt du aus: lösch Preis und Menge, dann zählt das Angebot nicht mit.",
      "Nur wenn alle gefüllten Angebote dieselbe Bezugsgröße haben (etwa kg oder Liter), markieren wir den niedrigsten Grundpreis. Stück, Gewicht und Volumen mischen wir nicht zu einem Sieger.",
    ],
    tip: "Gleicher Grundpreis heißt noch nicht gleiches Produkt. Marke, Haltbarkeit und Inhalt können den günstigeren Liter teurer machen, sobald du mehr davon brauchst.",
    related: ["grundpreis", "multipack-stueckpreis", "rabatt"],
    compute: computeVergleich,
  },
  {
    slug: "ratenkauf",
    title: "Ratenkauf",
    description: "Summe aus Anzahlung und Raten, gegen den Barpreis gerechnet.",
    category: "shopping",
    keywords: ["raten", "finanzierung", "ratenzahlung", "barpreis", "null prozent"],
    fields: [
      { id: "bar", label: "Barpreis", unit: "€", kind: "number", defaultValue: "899" },
      { id: "anzahlung", label: "Anzahlung", unit: "€", kind: "number", defaultValue: "0" },
      { id: "anzahl", label: "Anzahl der Raten", unit: "Stück", kind: "number", defaultValue: "24", integer: true },
      { id: "rate", label: "Höhe einer Rate", unit: "€", kind: "number", defaultValue: "42.5" },
    ],
    formula: [
      "Gesamt = Anzahlung + Anzahl der Raten × Ratenhöhe.",
      "Aufpreis = Gesamt − Barpreis. Ein negativer Aufpreis ist ein Vorteil gegenüber dem Barpreis.",
      "Der Aufpreis in Prozent ist Aufpreis ÷ Barpreis × 100. Bei einem Barpreis von 0 ist dieser Prozentsatz nicht definiert.",
      "Das ist der gezahlte Gesamtpreis, kein effektiver Jahreszins.",
    ],
    tip: "Null Prozent ist nur günstig, wenn der Barpreis nicht höher ist als anderswo. Die Summe aller Raten plus Anzahlung ist der Preis, den du wirklich zahlst. Stell ihn neben den Barpreis, nicht neben die Monatsrate.",
    related: ["annuitaetenkredit", "rabatt", "angebotsvergleich"],
    compute: computeRatenkauf,
  },
  {
    slug: "multipack-stueckpreis",
    title: "Multipack-Stückpreis",
    description: "Stückpreis der Packung, auf Wunsch gegen den Einzelkauf.",
    category: "shopping",
    keywords: ["multipack", "stückpreis", "gebinde", "packung", "einzelpreis"],
    fields: [
      { id: "packung", label: "Preis der Packung", unit: "€", kind: "number", defaultValue: "3.49" },
      { id: "stueck", label: "Stück in der Packung", unit: "Stück", kind: "number", defaultValue: "6", integer: true },
      { id: "einzel", label: "Einzelpreis", unit: "€", kind: "number", defaultValue: "0.79", hint: "Leer lassen, wenn du nur den Stückpreis der Packung willst." },
    ],
    formula: [
      "Stückpreis = Preis der Packung ÷ Stückzahl.",
      "Wenn du einen Einzelpreis einträgst: Vorteil der Packung = (Einzelpreis − Stückpreis) × Stückzahl.",
      "Ein negativer Vorteil heißt: die Packung ist je Stück teurer als der Einzelkauf.",
    ],
    tip: "Der Stückpreis der Großpackung ist nur dann ein Vorteil, wenn du die Menge verbrauchst, bevor sie abläuft oder verstaubt. Was du wegwirfst, war der teuerste Teil.",
    related: ["grundpreis", "angebotsvergleich", "rabatt"],
    compute: computeMultipack,
  },
]

const bySlug = new Map(calculators.map((calculator) => [calculator.slug, calculator]))

export function getCalculator(slug: string): Calculator | undefined {
  return bySlug.get(slug)
}

export function calculatorsInCategory(category: Calculator["category"]): Calculator[] {
  return calculators.filter((calculator) => calculator.category === category)
}

export function highlightedCalculators(): Calculator[] {
  return calculators.filter((calculator) => calculator.highlighted)
}

export function relatedCalculators(calculator: Calculator): Calculator[] {
  return calculator.related
    .map((slug) => bySlug.get(slug))
    .filter((item): item is Calculator => item !== undefined)
}
